export const apiConfig = {
  baseUrl:
    process.env.NEXT_PUBLIC_API_BASE_URL ??
    (process.env.NODE_ENV === "production"
      ? "https://api.vroomcar.com/v1"
      : "http://localhost:3001/v1"),
  internalBaseUrl:
    process.env.INTERNAL_API_BASE_URL ??
    (process.env.NODE_ENV === "production" ? "http://api-gateway.internal/v1" : "http://localhost:3001/v1"),
  enableMock: (process.env.NEXT_PUBLIC_ENABLE_API_MOCK ?? "false") === "true",
  timeoutMs: 20_000,
  timeoutDownloadMs: 120_000,
  timeoutUploadMs: 300_000,
  retryAttempts: 3,
  retryDelayMs: 400,
  retryMaxDelayMs: 5000,
  retryStatuses: [408, 413, 425, 429, 500, 502, 503, 504],
  cacheControlDefault: "public, s-maxage=1, stale-while-revalidate=59",
  cacheControlLong: "public, s-maxage=3600, stale-while-revalidate=86400",
  cacheControlShort: "public, s-maxage=60, stale-while-revalidate=300",
  cacheControlPrivate: "private, no-store, no-cache, max-age=0",
  cacheControlStatic: "public, max-age=31536000, immutable",
  defaultPerPage: 24,
  maxPerPage: 200,
  version: "1",
  endpoints: {
    auth: {
      login: "/auth/login",
      register: "/auth/register",
      logout: "/auth/logout",
      refresh: "/auth/refresh",
      forgotPassword: "/auth/forgot-password",
      resetPassword: "/auth/reset-password",
      verifyEmail: "/auth/verify-email",
      resendVerification: "/auth/verify-email/resend",
      oauthCallback: "/auth/oauth/:provider/callback",
      me: "/auth/me",
      impersonate: "/auth/impersonate/:userId",
      stopImpersonate: "/auth/impersonate/stop",
      mfaSetup: "/auth/mfa/setup",
      mfaVerify: "/auth/mfa/verify",
      mfaDisable: "/auth/mfa/disable",
      session: "/auth/session",
    },
    users: {
      root: "/users",
      byId: "/users/:id",
      me: "/users/me",
      profile: "/users/me/profile",
      preferences: "/users/me/preferences",
      password: "/users/me/password",
      email: "/users/me/email",
      phone: "/users/me/phone",
      avatar: "/users/me/avatar",
      tier: "/users/me/tier",
      activity: "/users/me/activity",
      addresses: "/users/me/addresses",
      addressById: "/users/me/addresses/:id",
      paymentCards: "/users/me/payment-cards",
      paymentCardById: "/users/me/payment-cards/:id",
      documents: "/users/me/documents",
      documentById: "/users/me/documents/:id",
    },
    vehicles: {
      root: "/vehicles",
      byId: "/vehicles/:id",
      bySlug: "/vehicles/slug/:slug",
      search: "/vehicles/search",
      makes: "/vehicles/makes",
      makeById: "/vehicles/makes/:id",
      models: "/vehicles/models",
      modelById: "/vehicles/models/:id",
      trims: "/vehicles/trims",
      trimById: "/vehicles/trims/:id",
      colors: "/vehicles/colors",
      options: "/vehicles/options",
      optionGroups: "/vehicles/option-groups",
      featured: "/vehicles/featured",
      newArrivals: "/vehicles/new-arrivals",
      priceDrops: "/vehicles/price-drops",
      similar: "/vehicles/:id/similar",
      compare: "/vehicles/compare",
      filters: "/vehicles/filters/meta",
      history: "/vehicles/:id/history",
      conditionReport: "/vehicles/:id/condition-report",
      warranty: "/vehicles/:id/warranty",
      inquire: "/vehicles/:id/inquire",
      scheduleTestDrive: "/vehicles/:id/test-drive",
      reserve: "/vehicles/:id/reserve",
      financing: "/vehicles/:id/financing",
      tradeIn: "/vehicles/:id/trade-in",
    },
    products: {
      root: "/products",
      byId: "/products/:id",
      bySlug: "/products/slug/:slug",
      search: "/products/search",
      brands: "/products/brands",
      brandById: "/products/brands/:id",
      categories: "/products/categories",
      categoryById: "/products/categories/:id",
      featured: "/products/featured",
      bestsellers: "/products/bestsellers",
      newArrivals: "/products/new-arrivals",
      onSale: "/products/on-sale",
      related: "/products/:id/related",
      upsell: "/products/:id/upsell",
      crossSell: "/products/:id/cross-sell",
      reviews: "/products/:id/reviews",
      reviewStats: "/products/:id/reviews/stats",
      createReview: "/products/:id/reviews",
      reviewById: "/products/reviews/:id",
      helpfulVote: "/products/reviews/:id/vote",
      attributes: "/products/attributes",
      attributeById: "/products/attributes/:id",
      inventory: "/products/:id/inventory",
      variants: "/products/:id/variants",
      variantById: "/products/variants/:id",
      filters: "/products/filters/meta",
    },
    cart: {
      root: "/cart",
      items: "/cart/items",
      itemById: "/cart/items/:id",
      updateItem: "/cart/items/:id",
      clear: "/cart/clear",
      applyCoupon: "/cart/coupon",
      removeCoupon: "/cart/coupon",
      shippingQuote: "/cart/shipping/quote",
      estimate: "/cart/estimate",
      convert: "/cart/convert",
      merge: "/cart/merge",
    },
    checkout: {
      initialize: "/checkout/initialize",
      prepare: "/checkout/prepare",
      process: "/checkout/process",
      confirm: "/checkout/:id/confirm",
      cancel: "/checkout/:id/cancel",
      paymentMethods: "/checkout/payment-methods",
      shippingMethods: "/checkout/shipping-methods",
      paymentIntent: "/checkout/payment-intent",
      capture: "/checkout/:id/capture",
    },
    orders: {
      root: "/orders",
      byId: "/orders/:id",
      byNumber: "/orders/number/:number",
      userOrders: "/users/me/orders",
      track: "/orders/:id/track",
      invoice: "/orders/:id/invoice",
      downloadInvoice: "/orders/:id/invoice/download",
      documents: "/orders/:id/documents",
      cancel: "/orders/:id/cancel",
      requestReturn: "/orders/:id/returns",
      returns: "/orders/:id/returns",
      returnById: "/orders/returns/:id",
      reorder: "/orders/:id/reorder",
      review: "/orders/:id/review",
    },
    wallet: {
      root: "/wallet",
      transactions: "/wallet/transactions",
      transactionById: "/wallet/transactions/:id",
      topUp: "/wallet/top-up",
      topUpIntent: "/wallet/top-up/intent",
      withdraw: "/wallet/withdraw",
      transfer: "/wallet/transfer",
      statement: "/wallet/statement",
      autoTopUp: "/wallet/auto-topup",
    },
    loyalty: {
      root: "/loyalty",
      ledger: "/loyalty/ledger",
      program: "/loyalty/program",
      tiers: "/loyalty/tiers",
      currentTier: "/loyalty/me/tier",
      earn: "/loyalty/earn",
      redeem: "/loyalty/redeem",
      exchange: "/loyalty/exchange",
      vouchers: "/loyalty/vouchers",
    },
    wishlists: {
      root: "/wishlists",
      byId: "/wishlists/:id",
      default: "/wishlists/default",
      items: "/wishlists/:id/items",
      itemById: "/wishlists/:id/items/:itemId",
      share: "/wishlists/:id/share",
      addToCart: "/wishlists/:id/add-to-cart",
    },
    referrals: {
      root: "/referrals",
      send: "/referrals/send",
      myCode: "/referrals/my-code",
      referralStats: "/referrals/stats",
    },
    coupons: {
      validate: "/coupons/validate",
      byCode: "/coupons/code/:code",
    },
    savedSearches: {
      root: "/saved-searches",
      byId: "/saved-searches/:id",
      toggleAlert: "/saved-searches/:id/alert",
      toggleFrequency: "/saved-searches/:id/frequency",
    },
    notifications: {
      root: "/notifications",
      byId: "/notifications/:id",
      unread: "/notifications/unread",
      markRead: "/notifications/:id/read",
      markAllRead: "/notifications/read-all",
      preferences: "/notifications/preferences",
    },
    support: {
      tickets: "/support/tickets",
      ticketById: "/support/tickets/:id",
      ticketMessages: "/support/tickets/:id/messages",
      closeTicket: "/support/tickets/:id/close",
      categories: "/support/categories",
      faq: "/support/faq",
      articles: "/support/articles",
      articleById: "/support/articles/:id",
      chatInit: "/support/chat/init",
    },
    appointments: {
      root: "/appointments",
      byId: "/appointments/:id",
      reschedule: "/appointments/:id/reschedule",
      cancel: "/appointments/:id/cancel",
      slots: "/appointments/slots",
      myAppointments: "/users/me/appointments",
    },
    static: {
      pages: "/pages/:slug",
      menu: "/static/menus/:location",
      banners: "/static/banners/:zone",
      footer: "/static/footer",
    },
    search: {
      global: "/search",
      autocomplete: "/search/autocomplete",
      suggestions: "/search/suggestions",
      trending: "/search/trending",
      recent: "/search/recent",
    },
    blog: {
      root: "/blog/posts",
      byId: "/blog/posts/:id",
      bySlug: "/blog/posts/slug/:slug",
      categories: "/blog/categories",
      tags: "/blog/tags",
      authors: "/blog/authors",
      authorById: "/blog/authors/:id",
      comments: "/blog/posts/:id/comments",
    },
    uploads: {
      presigned: "/uploads/presigned",
      presignedBulk: "/uploads/presigned/bulk",
      confirm: "/uploads/:key/confirm",
      remove: "/uploads/:key/remove",
    },
    analytics: {
      event: "/analytics/events",
      pageView: "/analytics/pageview",
    },
    health: {
      root: "/health",
      db: "/health/db",
      redis: "/health/redis",
      services: "/health/services",
    },
    regions: {
      countries: "/regions/countries",
      cities: "/regions/cities",
      zipcodes: "/regions/zipcodes/:code",
      shippingZones: "/regions/shipping-zones",
    },
  },
} as const;

export type ApiConfig = typeof apiConfig;
