import type { Locale, Currency, LanguageCode } from "@/types";

export const siteConfig = {
  name: "VroomCar",
  shortName: "VroomCar",
  description:
    "VroomCar — La plateforme automobile premium pour véhicules d'occasion, neufs et accessoires. Expérience d'achat inspirée des plus grandes marques.",
  slogan: "L'Excellence Automobile, Réinventée.",
  tagline: "Premium. Transparent. Sans Surprise.",
  url:
    process.env.NEXT_PUBLIC_SITE_URL ??
    (process.env.NODE_ENV === "production" ? "https://vroomcar.com" : "http://localhost:3000"),
  legal: {
    companyName: "VroomCar SARL",
    siret: "CI-ABJ-2024-01-001",
    tvaNumber: "CI123456789",
    registeredCapital: "50 000 000 FCFA",
    address: {
      line1: "Boulevard de la République",
      postalCode: "01",
      city: "Abidjan",
      country: "Côte d'Ivoire",
      countryCode: "CI",
    },
    email: {
      support: "contact@vroomcar.ci",
      sales: "ventes@vroomcar.ci",
      press: "presse@vroomcar.ci",
      careers: "recrutement@vroomcar.ci",
      legal: "legal@vroomcar.ci",
    },
    phones: {
      sales: "+225 01 23 45 67 89",
      support: "+225 01 23 45 67 89",
      concierge: "+225 01 23 45 67 89",
    },
  },
  brand: {
    primaryColor: "#253E38",
    secondaryColor: "#A7CD0F",
    accentColor: "#FEB300",
    darkColor: "#101418",
    lightColor: "#F8FAFC",
    logo: "/logo.svg",
    logoDark: "/logo-dark.svg",
    ogImage: "/og-image.png",
    favicon: "/favicon.ico",
  },
  defaults: {
    locale: "fr" as Locale,
    currency: "XOF" as Currency,
    language: "fr-FR" as LanguageCode,
    country: "CI",
    countryOptions: [
      { value: "CI", label: "Côte d'Ivoire", flag: "��", currency: "XOF" },
      { value: "SN", label: "Sénégal", flag: "��", currency: "XOF" },
      { value: "ML", label: "Mali", flag: "��", currency: "XOF" },
      { value: "BF", label: "Burkina Faso", flag: "��", currency: "XOF" },
      { value: "NE", label: "Niger", flag: "�🇪", currency: "XOF" },
      { value: "TG", label: "Togo", flag: "��", currency: "XOF" },
      { value: "BJ", label: "Bénin", flag: "��", currency: "XOF" },
      { value: "GH", label: "Ghana", flag: "🇬�", currency: "GHS" },
      { value: "NG", label: "Nigeria", flag: "��", currency: "NGN" },
    ],
    currencyOptions: [
      { value: "XOF", label: "Franc CFA", symbol: "FCFA" },
      { value: "EUR", label: "Euro", symbol: "€" },
      { value: "USD", label: "Dollar US", symbol: "$" },
      { value: "GBP", label: "Livre Sterling", symbol: "£" },
    ],
    languageOptions: [
      { value: "fr-FR", label: "Français", code: "fr", flag: "🇫🇷" },
      { value: "en-US", label: "English", code: "en", flag: "🇬🇧" },
      { value: "de-DE", label: "Deutsch", code: "de", flag: "🇩🇪" },
      { value: "es-ES", label: "Español", code: "es", flag: "🇪🇸" },
      { value: "it-IT", label: "Italiano", code: "it", flag: "🇮🇹" },
    ],
    timezone: "Africa/Abidjan",
    dateFormat: "dd/MM/yyyy",
    dateTimeFormat: "dd/MM/yyyy HH:mm",
    perPage: {
      small: 12,
      default: 24,
      large: 48,
      options: [12, 24, 48, 96],
    },
  },
  features: {
    vehicles: true,
    shop: true,
    appointments: true,
    concierge: true,
    financing: true,
    tradeIn: true,
    wallet: true,
    loyalty: true,
    referrals: true,
    wishlists: true,
    vehicleComparison: true,
    savedSearches: true,
    blog: true,
    reviews: true,
    multiCurrency: true,
    multiLanguage: true,
    darkMode: true,
  },
  navigation: {
    main: [
      { label: "Véhicules", href: "/vehicles" },
      { label: "Boutique", href: "/products" },
      { label: "Services", href: "/services" },
      { label: "Financement", href: "/financing" },
      { label: "À propos", href: "/about" },
    ],
    vehicles: [
      { label: "Tous les véhicules", href: "/vehicles" },
      { label: "Neufs", href: "/vehicles?condition=new" },
      { label: "Certifiés", href: "/vehicles?certified=true" },
      { label: "Électriques", href: "/vehicles?fuel=electric" },
      { label: "SUV", href: "/vehicles?body=suv" },
      { label: "Sportives", href: "/vehicles?body=sports" },
    ],
    shop: [
      { label: "Accessoires", href: "/products?category=accessories" },
      { label: "Pneumatiques", href: "/products?category=tires" },
      { label: "Entretien", href: "/products?category=care" },
      { label: "Électronique", href: "/products?category=electronics" },
      { label: "Intérieur", href: "/products?category=interior" },
      { label: "Performance", href: "/products?category=performance" },
    ],
  },
  social: {
    facebook: "https://facebook.com/vroomcar",
    instagram: "https://instagram.com/vroomcar",
    twitter: "https://twitter.com/vroomcar",
    linkedin: "https://linkedin.com/company/vroomcar",
    tiktok: "https://tiktok.com/@vroomcar",
    youtube: "https://youtube.com/@vroomcar",
  },
  seo: {
    robots: process.env.NODE_ENV === "production" ? "index, follow" : "noindex, nofollow",
    maxTitleLength: 65,
    maxDescriptionLength: 160,
    keywords: [
      "voiture d'occasion",
      "voiture neuve",
      "véhicule premium",
      "acheter voiture en ligne",
      "vroomcar",
      "vente automobile",
      "concessionnaire en ligne",
      "location avec option d'achat",
      "LOA",
      "leasing voiture",
      "supercar",
      "voiture collection",
    ],
  },
  business: {
    vatRate: 0.2,
    standardWarrantyMonths: 12,
    certifiedWarrantyMonths: 24,
    returnDays: 14,
    vehicleReturnDays: 7,
    freeShippingThreshold: 150,
    freeShippingThresholdCountry: "FR",
    standardShipping: {
      cost: 6.9,
      threshold: 150,
      deliveryDaysMin: 3,
      deliveryDaysMax: 5,
    },
    expressShipping: {
      cost: 14.9,
      deliveryDaysMin: 1,
      deliveryDaysMax: 2,
    },
    conciergeHourlyRate: 180,
    homeTestDriveFee: 0,
    appointmentSlotsStartHour: 9,
    appointmentSlotsEndHour: 19,
    appointmentSlotMinutes: 60,
    maxCompareVehicles: 4,
    maxWishlistsPerUser: 10,
    maxItemsPerWishlist: 50,
    cartSessionLifetimeHours: 7 * 24,
    vehicleReservationMinutes: 30,
    cartReservationMinutes: 15,
  },
  analytics: {
    googleAnalyticsId: process.env.NEXT_PUBLIC_GA_ID ?? "",
    googleTagManagerId: process.env.NEXT_PUBLIC_GTM_ID ?? "",
    hotjarId: process.env.NEXT_PUBLIC_HOTJAR_ID ?? "",
    amplitudeApiKey: process.env.NEXT_PUBLIC_AMPLITUDE_KEY ?? "",
    crispWebsiteId: process.env.NEXT_PUBLIC_CRISP_ID ?? "",
  },
  seoJsonLdEnabled: true,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.vroomcar.com" },
      { protocol: "https", hostname: "cdn.vroomcar.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "res.cloudinary.com" },
      { protocol: "https", hostname: "storage.googleapis.com" },
    ],
    vehiclePlaceholder: "/placeholders/vehicle.svg",
    productPlaceholder: "/placeholders/product.svg",
    userPlaceholder: "/placeholders/user.svg",
  },
  rateLimit: {
    apiWindowMs: 60_000,
    apiMaxRequests: 300,
    loginWindowMs: 15 * 60_000,
    loginMaxAttempts: 5,
  },
  payment: {
    providers: ["stripe", "apple_pay", "google_pay", "paypal", "klarna", "alma"] as const,
    defaultProvider: "stripe",
    threeDSecureThreshold: 250,
    allowedMethods: [
      "card",
      "apple_pay",
      "google_pay",
      "paypal",
      "klarna",
      "alma",
      "sepa_transfer",
      "bank_transfer",
      "wallet_credit",
    ],
    installments: [3, 4, 6, 10, 12, 24, 36],
    leasingOptions: {
      minDuration: 24,
      maxDuration: 60,
      mileageOptions: [10000, 15000, 20000, 25000, 30000],
      depositPercents: [0, 10, 20, 30, 40, 50],
    },
  },
  auth: {
    providers: ["credentials", "google", "apple"] as const,
    passwordMinLength: 10,
    passwordRequireSymbols: true,
    passwordRequireNumbers: true,
    passwordRequireUppercase: true,
    rememberMeDays: 30,
    sessionMaxAgeDays: 7,
    verificationTokenLifetimeMinutes: 60,
    passwordResetTokenLifetimeMinutes: 30,
    mfaEnabled: true,
    mfaMethods: ["totp", "sms", "email"] as const,
    requireEmailVerification: true,
  },
} as const;

export type SiteConfig = typeof siteConfig;
